### ISSUE TITLE
dataset download problem

### ISSUE THREAD

**Issue by ShanglinLi** [yunkezhang/TCVOM#1]

**Comment by ShanglinLi** [comment]
it seems that I can not download the dataset from the link provided.

**Comment by yunkezhang** [comment]
Hi, we'll mirror the dataset to BaiduYun ASAP.
In the meantime, I'm afraid you'll need a proxy for OneDrive.

**Comment by yunkezhang** [comment]
Updated BaiduYun link in README.md

**Comment by ShanglinLi** [comment]
Got it, thanks a lot.

**Comment by liangyufz** [comment]
> Hi, we'll mirror the dataset to BaiduYun ASAP. In the meantime, I'm afraid you'll need a proxy for OneDrive.

hello，the speed of OneDrive is still too slow  even I set a proxy.
can the supplyments and  *.pth be sent to BaiduYun ?
thanks a lot!

**Comment by yunkezhang** [comment]
> > Hi, we'll mirror the dataset to BaiduYun ASAP. In the meantime, I'm afraid you'll need a proxy for OneDrive.
> 
> hello，the speed of OneDrive is still too slow even I set a proxy. can the supplyments and *.pth be sent to BaiduYun ? thanks a lot!

https://pan.baidu.com/s/1bD4Es5d5EM4PRsGRwJBpPA
Code: t6rb

**Comment by liangyufz** [comment]
> > > Hi, we'll mirror the dataset to BaiduYun ASAP. In the meantime, I'm afraid you'll need a proxy for OneDrive.
> > 
> > 
> > hello，the speed of OneDrive is still too slow even I set a proxy. can the supplyments and *.pth be sent to BaiduYun ? thanks a lot!
> 
> https://pan.baidu.com/s/1bD4Es5d5EM4PRsGRwJBpPA Code: t6rb

thanks ！
