### ISSUE TITLE
artifacts near the boundary of the object

### ISSUE THREAD

**Issue by Hongje** [yunkezhang/TCVOM#3]
Thank you for sharing your great work!

When I ran `pred_vmn.py` using the provided dataset (VideoMatting108) and pretrained model (FBA_TAM_Lim_Ltc_Laf.pth), the result of alpha matte seems to be wrong.

![00000_pred](https://user-images.githubusercontent.com/33046378/123135014-5286ad80-d48c-11eb-941f-d1628dea1628.png)

The above result is `animal_still/dove/00000_pred.png`, and artifacts appear very much near the boundary of the object.
The running script is
`python pred_vmn.py --model fba --data ./data/VideoMatting108 --load ./weights/FBA_TAM_Lim_Ltc_Laf.pth --trimap narrow --save ./results/fba_vmn`

I got some warnings below and it looks like this could be the problem.
```
Missing keys: ['decoder.fam.key_conv.bias', 'decoder.fam.key_conv.weight', 'decoder.fam.query_conv.bias', 'decoder.fam.query_conv.weight', 'decoder.fam.value_conv.bias', 'decoder.fam.value_conv.weight']
Unexpected keys: []
```

**Comment by TomoshibiAkira** [comment]
Hi, thank you for your interest in our work!

Just found out that the weight file for ``FBA`` was named in reverse. The ``FBA_SINGLE_Lim.pth`` is actually the file for ``FBA+TAM`` and vice versa.
I've already corrected naming in our weight sharing folder.

Just in case, I'll give SHA-1 checksum for the two files:
For ``FBA+F`` (baseline, 132MB):  12CD1DDDADA7AA797C8B71F0B115FEDD50DD1EF1
For ``FBA+TAM`` (our method, 139MB): 8343DF08DB173BF6B528CC8C62313CB03941B618

Closed.

**Comment by yunkezhang** [comment]
Hi, thank you for your interest in our work!

Just found out that weight files' for  ``FBA`` are reversed. The weight file for ``FBA+F`` should be the weight file for ``FBA+TAM`` and vice versa.
I've already corrected the naming in our weight sharing folder, again, thank you for the report.

Just in case I'll also share the SHA-1 checksum below:
For ``FBA+F`` (baseline method, 132MB): ``12CD1DDDADA7AA797C8B71F0B115FEDD50DD1EF1``
For ``FBA+TAM`` (our method, 139MB): ``8343DF08DB173BF6B528CC8C62313CB03941B618``

Closed.
