### ISSUE TITLE
question for pred_test.py

### ISSUE THREAD

**Issue by AwA1245** [yunkezhang/TCVOM#4]
I want test my own videos
but I don't know how to get the trimap
how can I get these images?

**Comment by yunkezhang** [comment]
For the exact description, you can refer to Section 1.3 from the paper ```Image and Video Matting: A Survey```.

tl;dr: Draw the region where you want to extract alpha matte as the trimap unknown region (grayscale 128), and fill other regions as background (grayscale 0) or foreground (grayscale 255). You can find some examples from matting datasets such as ours or alphamatting.com (http://alphamatting.com/datasets.php)
