### ISSUE TITLE
您好，我刚才看了您的补充材料的视频，效果很惊艳

### ISSUE THREAD

**Issue by zhanghongyong123456** [yunkezhang/TCVOM#7]
我有几个问题想问一下：
1.我如果测试自己的图像或者视频该如何制作自己的测试数据集
2.对于推理时间达到什么速度，能否实现实时效果
3.相比于Robust High-Resolution Video Matting with Temporal Guidance最近开源的这个项目，效果如何：抠像质量上（头发丝、半透明物体）；速度上4k实时（我们项目未来能达到吗）

**Comment by yunkezhang** [comment]
您好，感谢您对这个项目的关注。
1、项目README里面已经写了，请参照"Inference on test video clips"部分
2、在GCA的backbone上在1080Ti上1080p的inference速度约为1FPS.
3、metric由于我们没有在他们的数据集上训练所以不好一对一比较；速度上由于我们使用的都是各基于deep learning的image matting算法的backbone，若不针对高分辨率图像进行任何优化较难以达到实时。
